services:

  backend:
    build:
      context: ./backend
    container_name: publicidade_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: publicidade_db
    restart: always
    environment:
      POSTGRES_DB: publicidade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"